"""tables

Revision ID: 120a4a9e8d38
Revises:
Create Date: 2026-04-05 00:22:31.409470

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "120a4a9e8d38"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchant",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("ix_merchant_deleted_at", "merchant", ["deleted_at"], unique=False)
    op.create_index("ix_merchant_is_active", "merchant", ["is_active"], unique=False)
    op.create_table(
        "outbox_message",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("topic", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_outbox_messages_status_created_at",
        "outbox_message",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "balance",
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("reserved_amount", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("merchant_id"),
    )
    op.create_table(
        "merchant_credential",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("api_key_prefix", sa.String(), nullable=False),
        sa.Column("api_key_hash", sa.String(), nullable=False),
        sa.Column("secret_key_encrypted", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key_prefix"),
    )
    op.create_index(
        "ix_merchant_credential_is_active", "merchant_credential", ["is_active"], unique=False
    )
    op.create_index(
        "ix_merchant_credential_merchant_id", "merchant_credential", ["merchant_id"], unique=False
    )
    op.create_table(
        "payment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("merchant_order_id", sa.String(), nullable=False),
        sa.Column("external_invoice_id", sa.String(), nullable=False),
        sa.Column("provider_payment_id", sa.String(), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("provider_status", sa.String(), nullable=True),
        sa.Column("failure_reason", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchant.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_invoice_id"),
        sa.UniqueConstraint("provider_payment_id"),
    )
    op.create_index(
        "ix_payments_external_invoice_id", "payment", ["external_invoice_id"], unique=False
    )
    op.create_index("ix_payments_merchant_id", "payment", ["merchant_id"], unique=False)
    op.create_index("ix_payments_status", "payment", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_payments_status", table_name="payment")
    op.drop_index("ix_payments_merchant_id", table_name="payment")
    op.drop_index("ix_payments_external_invoice_id", table_name="payment")
    op.drop_table("payment")
    op.drop_index("ix_merchant_credential_merchant_id", table_name="merchant_credential")
    op.drop_index("ix_merchant_credential_is_active", table_name="merchant_credential")
    op.drop_table("merchant_credential")
    op.drop_table("balance")
    op.drop_index("ix_outbox_messages_status_created_at", table_name="outbox_message")
    op.drop_table("outbox_message")
    op.drop_index("ix_merchant_is_active", table_name="merchant")
    op.drop_index("ix_merchant_deleted_at", table_name="merchant")
    op.drop_table("merchant")
    # ### end Alembic commands ###
